# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 182409f30e188881d02f33cccac689d1dfcc258d6c0312a50967c4a8550878fc61cb93f499e691c214e75aace91b7fb178b11ee41260353aa6c42187b5488ccf

test:
  secret_key_base: 810846591cd90947d28388bdb383047c46ecdaf36dc680e9284233780c1221b1999a694e7cd76077507a2203d47bc7996e4ad80267f94aa5c85b5ad57125aac3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
